# Generated by Django 5.2 on 2025-11-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomplishmentrecord',
            name='description',
        ),
    ]
