# Generated by Django 5.2 on 2025-11-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osas', '0002_remove_accomplishmentrecord_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity',
            field=models.TextField(),
        ),
    ]
