# Generated by Django 5.2 on 2025-11-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osas', '0003_alter_useractivitylog_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_coadviser_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Co-Adviser Department'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_coadviser_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Co-Adviser Email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_coadviser_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Co-Adviser Name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_coadviser_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Co-Adviser Phone'),
        ),
    ]
