# Generated by Django 5.2 on 2025-11-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osas', '0004_organization_organization_coadviser_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='slots_available',
        ),
    ]
