# Generated by Django 5.2 on 2026-01-17 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osas', '0005_remove_scholarship_slots_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('hearing_scheduled', 'Hearing Scheduled'), ('ongoing_hearing', 'Ongoing Hearing'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='under_review', max_length=20),
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_type', models.CharField(choices=[('1st_hearing', '1st Hearing'), ('2nd_hearing', '2nd Hearing'), ('other', 'Other Hearing')], max_length=20)),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('location', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='osas.complaint')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['schedule_date', 'schedule_time'],
            },
        ),
    ]
