# Generated by Django 5.2 on 2026-01-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osas', '0006_alter_complaint_status_hearing'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hearing_count',
            field=models.IntegerField(default=0, help_text='Number of hearings conducted'),
        ),
    ]
