# Generated by Django 5.2 on 2026-01-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osas', '0007_complaint_hearing_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='hearing_count',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='hearing_type',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('1st_hearing', '1st Hearing'), ('2nd_hearing', '2nd Hearing'), ('other_hearing', 'Other Hearing'), ('ongoing_hearing', 'Ongoing Hearing'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='under_review', max_length=20),
        ),
    ]
