# Generated by Django 5.2 on 2026-01-17 18:41:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osas', '0008_remove_complaint_hearing_count_and_more'),
    ]

    operations = [
        # First remove the unique_together constraint from OJTRequirement
        migrations.AlterUniqueTogether(
            name='ojtrequirement',
            unique_together=set(),
        ),
        # Remove foreign keys
        migrations.RemoveField(
            model_name='ojtrequirement',
            name='application',
        ),
        migrations.RemoveField(
            model_name='ojtreport',
            name='application',
        ),
        migrations.RemoveField(
            model_name='ojtreport',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='ojtreport',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='ojtreport',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='ojtreportattachment',
            name='report',
        ),
        migrations.RemoveField(
            model_name='ojtrequirement',
            name='verified_by',
        ),
        # Remove available_slots field
        migrations.RemoveField(
            model_name='ojtcompany',
            name='available_slots',
        ),
        # Delete the models
        migrations.DeleteModel(
            name='OJTApplication',
        ),
        migrations.DeleteModel(
            name='OJTReport',
        ),
        migrations.DeleteModel(
            name='OJTReportAttachment',
        ),
        migrations.DeleteModel(
            name='OJTRequirement',
        ),
    ]