# Generated by Django 5.2 on 2026-01-17 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osas', '0009_auto_20260117_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtcompany',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='ojtcompany',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ojtcompany',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updated_ojt_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
